name: Test GitHub Actions

on:
  push:
    branches:
      - main
      
jobs:
  First-Jobs:
    runs-on: ubuntu-latest

    steps:
      - name: Welcome Step
        run: echo "Welcome First Step"
        
      - name: Checkout Repo
        uses: actions/checkout@v4
  
      - name: List Files
        run: ls -la
